scaling: scaling.c
	g++ scaling.c -o scaling.exe -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 && ./scaling

shearing: shearing.c
	g++ shearing.c -o shearing.exe -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 && ./shearing < t.txt