translation: translation.c
	g++ translation.c -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 && ./a
reflection: reflection.c
	g++ reflection.c -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 && ./a
rotation: rotation.c
	g++ rotation.c -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 && ./a
